---
openapi: 3.0.1
info:
  title: Ayanitech API Documentation
  version: v1
paths:
  "/api/v1/get_output":
    parameters:
    - name: space_id
      in: path
      description: space_id
      required: true
      schema:
        type: string
    post:
      summary: get_output conversation
      tags:
      - Conversations
      security:
      - bearerAuth: []
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                input:
                  type: string
              required:
              - input
              - tokens
              - timeout
  "/api/v1/password/forgot":
    post:
      summary: forgot password
      tags:
      - Users
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
              required:
              - email
  "/api/v1/password/update":
    post:
      summary: update password
      tags:
      - Users
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                token:
                  type: string
                password:
                  type: string
              required:
              - email,
              - token,
              - password
  "/api/v1/password/reset":
    post:
      summary: reset password
      tags:
      - Users
      security:
      - bearerAuth: []
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                password:
                  type: string
                confirmation_password:
                  type: string
              required:
              - password,
              - confirmation_password
  "/api/v1/spaces":
    get:
      summary: list spaces
      tags:
      - Spaces
      security:
      - bearerAuth: []
      responses:
        '200':
          description: successful
    post:
      summary: create space
      tags:
      - Spaces
      security:
      - bearerAuth: []
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
              required:
              - name
  "/api/v1/spaces/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show space
      tags:
      - Spaces
      security:
      - bearerAuth: []
      responses:
        '200':
          description: successful
    patch:
      summary: update space
      tags:
      - Spaces
      security:
      - bearerAuth: []
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
              required:
              - name
    put:
      summary: update space
      tags:
      - Spaces
      security:
      - bearerAuth: []
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
              required:
              - name
    delete:
      summary: delete space
      tags:
      - Spaces
      security:
      - bearerAuth: []
      responses:
        '200':
          description: successful
  "/api/v1/users":
    post:
      summary: User Signup
      tags:
      - Users
      parameters: []
      responses:
        '201':
          description: User created
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: object
                  properties:
                    email:
                      type: string
                    password:
                      type: string
                    name:
                      type: string
                  required:
                  - email
                  - password
                  - name
                  - role
  "/api/v1/users/sign_in":
    post:
      summary: User Signin
      tags:
      - Users
      parameters: []
      responses:
        '201':
          description: Session created
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: object
                  properties:
                    email:
                      type: string
                    password:
                      type: string
                  required:
                  - email
                  - password
  "/api/v1/users/sign_out":
    delete:
      summary: delete session
      tags:
      - Users
      security:
      - bearerAuth: []
      responses:
        '200':
          description: successful
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
